### ISSUE TITLE
Assign a shortcut for the one-click action

### ISSUE THREAD

**Issue by kirtan403** [chrschorn/oneclick-send-to-trello#3]
A shortcut can be invoked after selecting the text or without selecting, which ultimately saves the selected text / current page respectively without mouse click or right clicking.

**Comment by chrschorn** [comment]
It is already possible to assign a hotkey to the default action (pressing the extension button in the top right) by using the built-in way of Chrome. It's here: chrome://extensions/shortcuts

Assigning an additional button for selection would be possible, but it would not be as robust as the right-click way, because right-click has "special abilities" in Chrome. It can collect information even in embedded web pages and cases where the "manual way" throws an error (although it strips all new lines etc.).

**Comment by chrschorn** [comment]
Won't implement - doable via standard chrome shortcuts!
